### PR TITLE
Using circmean to get circular mean

### LINKED ISSUE #213: Incorrect telescope pointing
This is related to #60 and  #66.

Looks like the RA_PNT isn't getting correctly set. I'm using `v0.5.2-preprocessing-v490.7`.  Here's what the datastore.obs_table reports for both point like and full enclosure IRFs:

image

https://github.com/VERITAS-Observatory/V2DL3/blob/ee2a5fc6a06cfe1a826db9073fb09536357033b9/pyV2DL3/eventdisplay/fillEVENTS.py#L194-L209

Replacing the `arctan2` function with `scipy.stats.circmean` seems to give a consistent answer:

```
def __get_average_pointing(file, runNumber):
    """
    Return circular mean RA and average DEC of telescope pointing

    """
    pointingDataReduced = file[
        f"run_{runNumber}/stereo/pointingDataReduced"].arrays(library="np")
    avRA = np.rad2deg(
        np.arctan2(
            np.sum(np.sin(pointingDataReduced["TelRAJ2000"])),
            np.sum(np.cos(pointingDataReduced["TelRAJ2000"])),
        )
    )
    avDec = np.mean(np.rad2deg(pointingDataReduced["TelDecJ2000"]))

    return avRA, avDec


def __get_average_pointing2(file, runNumber):
    """
    Return circular mean RA and average DEC of telescope pointing

    """
    pointingDataReduced = file[
        f"run_{runNumber}/stereo/pointingDataReduced"].arrays(library="np")

    n = len(pointingDataReduced["TelRAJ2000"])
    avRA = np.rad2deg(
        circmean(pointingDataReduced["TelRAJ2000"])
    )
    avDec = np.mean(np.rad2deg(pointingDataReduced["TelDecJ2000"]))

    return avRA, avDec
```

```
__get_average_pointing(file,run)
> (-107.18294548529406, 39.75928023998721)
__get_average_pointing2(file,run)
> (252.81705451470597, 39.75928023998721)
```

I didn't look too much into it but it looks like `circmean` applies a phase correction. 
See:
https://github.com/scipy/scipy/blob/44e4ebaac992fde33f04638b99629d23973cb9b2/scipy/stats/_morestats.py#L4338-L4417

### PR DESCRIPTION
**Pull request by steob92**
Resolves #213

Using `scipy.stats.circmean` to get the circular mean when getting the average RA.

### CODE REVIEW

**Review by tobiaskleiner — APPROVED** [review]
Thanks @steob92! The scipy implementation now adds the phase transition `res[res < 0] += 2*pi`. (Previous negative values are also working with gammapy/astropy.) You can merge.

**Comment by GernotMaier** [comment]
@steob92 , @tobiaskleiner - does this require a re-processing? How significant is the change? Does it justify a new release of V2DL3?

**Comment by tobiaskleiner** [comment]
@GernotMaier @steob92 not sure it is needed. There is no effect on the coordinate, the calculation was the same implementation as in scipy except for the phase shift (i.e. Ra coordinate `Ra=-150` --> `Ra=210`). Maybe we can wait for another major release (if happening) otherwise we reprocess in a few months?

**Comment by GernotMaier** [comment]
running v2dl3 takes a day, so it is not a computing issue. I just need to know.

**Comment by steob92** [comment]
@GernotMaier I originally started looking into this because when querying a large datastore, I wouldn't find the correct number of runs. 

When using the high level interface (config + Analysis, for example: https://docs.gammapy.org/1.2/tutorials/analysis-2d/ring_background.html). The coordinates passed to the `obs_cone` will be used to query the observation table which will use `RA/DEC_PNT`. See:
https://docs.gammapy.org/1.2/_modules/gammapy/data/obs_table.html#ObservationTable.select_observations

With the current pre-processed files, one needs to generate a runlist for a region of interest using VLISTBUILDER. I think VLISTBUILDER is still semi offline. We lost the ability to automatically update it, I'm also not sure if it was updated with runs beyond 2018...  

I think it's worth reprocessing...  This fix would remove the need for VLISTBUILDER when running a gammapy analysis. But I'm also not the one who will have to babysit the scripts!

**Comment by GernotMaier** [comment]
@steob92 - could you release a new version? 0.6.0?

**Pull request merged**
