### PR TITLE
Duplicate the irf values for EFFAREA and EDISP when one wobble in stored irf

### PR DESCRIPTION
**Pull request by sona-patel**
Addressing #87

### CODE REVIEW

**Comment by GernotMaier** [comment]
Could you explain again if you are addressing an issue in gammapy here or in V2DL3? Question is if we should ask gammapy to be able to handle these type of IRFs.

**Review by tobiaskleiner — APPROVED** [review]

**Comment by sona-patel** [comment]
No, error occurs in Gammapy because of incorrect DL3 file, so its issue in V2DL3.

**Comment by GernotMaier** [comment]
So where in the DL3 data standard is this required? I don't see that in the gamma-ray data format.

**Comment by sona-patel** [comment]
Isn't it rule of thumb that there should be one to one corresponds between axes and data?  Do we need to go to DL3 data standard for this?

**Comment by GernotMaier** [comment]
We need to follow the standard by the letter, anything else will lead to problems in the future.

If gammapy does not follow the standard, then we need to ask for a change - but please check for the gamma-ray format page if there are any requirements on the number of bins given per axis. We definitely shouldn't put work arounds into the code for issues which should be solved some where else (we could add it temporarily, but then it should be clearly indicated)

**Comment by GernotMaier** [comment]
Let's follow this up, is this a correct description of the issue?
- V2DL3 is providing IRFs with all axes included. The field of view axis (THETA_LO, THETA_HI) has a single bin only.
- gammapy requires that axes have at least two bins

If this is the case, then I think it is a gammapy issue. There is nowhere in the GADF standard a requirement that axes need to have more than one bin.

**Comment by sona-patel** [comment]
> Let's follow this up, is this a correct description of the issue?
> 
> * V2DL3 is providing IRFs with all axes included. The field of view axis (THETA_LO, THETA_HI) has a single bin only.
> * gammapy requires that axes have at least two bins
> 
> If this is the case, then I think it is a gammapy issue. There is nowhere in the GADF standard a requirement that axes need to have more than one bin.

Yes this is the correct description of the issue!

**Comment by GernotMaier** [comment]
I am accepting this now, although it is clearly a fudge. Added a warning when this is used and raise an error not if this is used for full-enclosure IRFs.

We need to find a better solution for the future, IRFs in gammapy seem to have the functionality to have no offset dependency. To not forget it, I am opening the issue #168

**Review by GernotMaier — APPROVED** [review]

**Comment by sona-patel** [comment]
Checked on rhv run 70323 with gammapy-0.20.1 - works without error!

**Pull request merged**
