### PR TITLE
Simplified pip and conda environment; pypi deployment

### PR DESCRIPTION
**Pull request by GernotMaier**
This pull requests simplifies installation and usage of V2DL3 significantly.

A simple `pip install v2dl3` should do all and then we call the three scripts as command line tools:
- `v2dl3-vegas`
- `v2dl3-generate-index-file`
- `v2dl3-eventdisplay`

It is very nice that we can use the same installation for eventdisplay and vegas flavours (at this point only for pip; could do this like also in future for the conda environments).

Replaces also setup.py by the more modern pyproject.toml approach.

Other changes:

- updates README accordingly
-  add github action workflow for deployment to pypi (at this point to TestPyPi, see [here](https://test.pypi.org/project/v2dl3/0.4.0.dev1/) to see how nice it will look like)

### CODE REVIEW

**Comment by GernotMaier** [comment]
@matthew-w-lundy @deividribeiro - could you have a look why the vegas workflow is failing? I am not sure I understand the different step of docker generation and pip installation. Maybe it is a small thing only - having this PR included would really by nice!

**Comment by matthew-w-lundy** [comment]
Appears to be how in the docker image we are pip installing. Locally running the instructions work in a clean conda environment. I will see if I can modify the test to reasonably still pass with changes to the install.

**Comment by GernotMaier** [comment]
@matthew-w-lundy - any progress on this issue? 

Being able to merge this PR would really be nice, as it simplifies installation.

**Comment by matthew-w-lundy** [comment]
Taking a look at this again today to try and resolve

**Comment by deividribeiro** [comment]
@GernotMaier I've uploaded a new vegas docker image to the workflow - can you resolve the conflict in this PR to trigger the actions so that we may be able to merge? The new docker image is updated to a python3 environment so the toml/pip issues should go away.

**Comment by GernotMaier** [comment]
@deividribeiro - the v2dl3-vegas-CI is failing. Can you have a look?

**Comment by tmcahill** [comment]
Good to use image history if possible, I can probably get them if not. Will follow up with @deividribeiro on slack.

**Comment by deividribeiro** [comment]
wooo! done. This PR should now be ok.

**Pull request merged**
